/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CmccGPRSber130"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CallEventRecordType_H_
#define	_CallEventRecordType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CallEventRecordType {
	CallEventRecordType_sgsnPDPRecord	= 18,
	CallEventRecordType_ggsnPDPRecord	= 19,
	CallEventRecordType_sgsnMMRecord	= 20,
	CallEventRecordType_sgsnSMORecord	= 21,
	CallEventRecordType_sgsnSMTRecord	= 22
} e_CallEventRecordType;

/* CallEventRecordType */
typedef long	 CallEventRecordType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallEventRecordType;
asn_struct_free_f CallEventRecordType_free;
asn_struct_print_f CallEventRecordType_print;
asn_constr_check_f CallEventRecordType_constraint;
ber_type_decoder_f CallEventRecordType_decode_ber;
der_type_encoder_f CallEventRecordType_encode_der;
xer_type_decoder_f CallEventRecordType_decode_xer;
xer_type_encoder_f CallEventRecordType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CallEventRecordType_H_ */
