/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CmccGPRSber130"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_CallDurationC_H_
#define	_CallDurationC_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CallDurationC */
typedef struct CallDurationC {
	long	 peak;
	long	 offPeak;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CallDurationC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallDurationC;

#ifdef __cplusplus
}
#endif

#endif	/* _CallDurationC_H_ */
