/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CmccGPRSber130"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ConsolidationResult_H_
#define	_ConsolidationResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConsolidationResult {
	ConsolidationResult_normal	= 0,
	ConsolidationResult_notNormal	= 1,
	ConsolidationResult_forInterSGSNConsolidation	= 2,
	ConsolidationResult_reachLimit	= 3,
	ConsolidationResult_onlyOneCDRGenerated	= 4
} e_ConsolidationResult;

/* ConsolidationResult */
typedef long	 ConsolidationResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConsolidationResult;
asn_struct_free_f ConsolidationResult_free;
asn_struct_print_f ConsolidationResult_print;
asn_constr_check_f ConsolidationResult_constraint;
ber_type_decoder_f ConsolidationResult_decode_ber;
der_type_encoder_f ConsolidationResult_encode_der;
xer_type_decoder_f ConsolidationResult_decode_xer;
xer_type_encoder_f ConsolidationResult_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ConsolidationResult_H_ */
