/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CmccGPRSber130"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_ManagementExtensions_H_
#define	_ManagementExtensions_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ManagementExtension.h"
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ManagementExtensions */
typedef struct ManagementExtensions {
	A_SET_OF(ManagementExtension_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManagementExtensions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManagementExtensions;

#ifdef __cplusplus
}
#endif

#endif	/* _ManagementExtensions_H_ */
