/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CmccGPRSber130"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_QoSInformation_H_
#define	_QoSInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "QoSReliability.h"
#include "QoSDelay.h"
#include "QoSPrecedence.h"
#include "QoSPeakThroughput.h"
#include "QoSMeanThroughput.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* QoSInformation */
typedef struct QoSInformation {
	QoSReliability_t	 reliability;
	QoSDelay_t	 delay;
	QoSPrecedence_t	 precedence;
	QoSPeakThroughput_t	 peakThroughput;
	QoSMeanThroughput_t	 meanThroughput;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} QoSInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QoSInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _QoSInformation_H_ */
