/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CmccGPRSber130"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#include <asn_internal.h>

#include "QoSInformation.h"

static asn_TYPE_member_t asn_MBR_QoSInformation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct QoSInformation, reliability),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoSReliability,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"reliability"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct QoSInformation, delay),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoSDelay,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"delay"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct QoSInformation, precedence),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoSPrecedence,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"precedence"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct QoSInformation, peakThroughput),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoSPeakThroughput,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"peakThroughput"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct QoSInformation, meanThroughput),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoSMeanThroughput,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"meanThroughput"
		},
};
static ber_tlv_tag_t asn_DEF_QoSInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_QoSInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* reliability at 268 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* delay at 269 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* precedence at 270 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* peakThroughput at 271 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* meanThroughput at 273 */
};
static asn_SEQUENCE_specifics_t asn_SPC_QoSInformation_specs_1 = {
	sizeof(struct QoSInformation),
	offsetof(struct QoSInformation, _asn_ctx),
	asn_MAP_QoSInformation_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_QoSInformation = {
	"QoSInformation",
	"QoSInformation",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_QoSInformation_tags_1,
	sizeof(asn_DEF_QoSInformation_tags_1)
		/sizeof(asn_DEF_QoSInformation_tags_1[0]), /* 1 */
	asn_DEF_QoSInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_QoSInformation_tags_1)
		/sizeof(asn_DEF_QoSInformation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_QoSInformation_1,
	5,	/* Elements count */
	&asn_SPC_QoSInformation_specs_1	/* Additional specs */
};

