/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CmccGPRSber130"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_QoSPeakThroughput_H_
#define	_QoSPeakThroughput_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum QoSPeakThroughput {
	QoSPeakThroughput_unspecified	= 0,
	QoSPeakThroughput_upTo100OctetPs	= 1,
	QoSPeakThroughput_upTo200OctetPs	= 2,
	QoSPeakThroughput_upTo400OctetPs	= 3,
	QoSPeakThroughput_upTo800OctetPs	= 4,
	QoSPeakThroughput_upTo1600OctetPs	= 5,
	QoSPeakThroughput_upTo3200OctetPs	= 6,
	QoSPeakThroughput_upTo6400OctetPs	= 7,
	QoSPeakThroughput_upTo12800OctetPs	= 8,
	QoSPeakThroughput_upTo25600OctetPs	= 9
} e_QoSPeakThroughput;

/* QoSPeakThroughput */
typedef long	 QoSPeakThroughput_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QoSPeakThroughput;
asn_struct_free_f QoSPeakThroughput_free;
asn_struct_print_f QoSPeakThroughput_print;
asn_constr_check_f QoSPeakThroughput_constraint;
ber_type_decoder_f QoSPeakThroughput_decode_ber;
der_type_encoder_f QoSPeakThroughput_encode_der;
xer_type_decoder_f QoSPeakThroughput_decode_xer;
xer_type_encoder_f QoSPeakThroughput_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _QoSPeakThroughput_H_ */
