/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CmccGPRSber130"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_RECORDSequenceNumber_H_
#define	_RECORDSequenceNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GSNAddress.h"
#include "RecordNumber.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RECORDSequenceNumber */
typedef struct RECORDSequenceNumber {
	GSNAddress_t	 gsnAddress;
	struct recordNumberList {
		A_SEQUENCE_OF(RecordNumber_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} recordNumberList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RECORDSequenceNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RECORDSequenceNumber;

#ifdef __cplusplus
}
#endif

#endif	/* _RECORDSequenceNumber_H_ */
