/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CmccGPRSber130"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_RecordNumber_H_
#define	_RecordNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RecordNumber */
typedef long	 RecordNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RecordNumber;
asn_struct_free_f RecordNumber_free;
asn_struct_print_f RecordNumber_print;
asn_constr_check_f RecordNumber_constraint;
ber_type_decoder_f RecordNumber_decode_ber;
der_type_encoder_f RecordNumber_encode_der;
xer_type_decoder_f RecordNumber_decode_xer;
xer_type_encoder_f RecordNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RecordNumber_H_ */
