/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CmccGPRSber130"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SGSNSMORecord_H_
#define	_SGSNSMORecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CallEventRecordType.h"
#include "IMSI.h"
#include "IMEI.h"
#include "MSISDN.h"
#include "MSNetworkCapability.h"
#include "AddressString.h"
#include "RecordingEntity.h"
#include "LocationAreaCode.h"
#include "RoutingAreaCode.h"
#include "CellId.h"
#include "MessageReference.h"
#include "TimeStamp.h"
#include "NodeID.h"
#include "LocalSequenceNumber.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SGSNSMORecord_PR {
	SGSNSMORecord_PR_recordType,	/* Member recordType is present */
	SGSNSMORecord_PR_servedIMSI,	/* Member servedIMSI is present */
	SGSNSMORecord_PR_servedIMEI,	/* Member servedIMEI is present */
	SGSNSMORecord_PR_servedMSISDN,	/* Member servedMSISDN is present */
	SGSNSMORecord_PR_msNetworkCapability,	/* Member msNetworkCapability is present */
	SGSNSMORecord_PR_serviceCentre,	/* Member serviceCentre is present */
	SGSNSMORecord_PR_recordingEntity,	/* Member recordingEntity is present */
	SGSNSMORecord_PR_locationArea,	/* Member locationArea is present */
	SGSNSMORecord_PR_routingArea,	/* Member routingArea is present */
	SGSNSMORecord_PR_cellIdentity,	/* Member cellIdentity is present */
	SGSNSMORecord_PR_messageReference,	/* Member messageReference is present */
	SGSNSMORecord_PR_originationTime,	/* Member originationTime is present */
	SGSNSMORecord_PR_smsResult,	/* Member smsResult is present */
	SGSNSMORecord_PR_recordExtensions,	/* Member recordExtensions is present */
	SGSNSMORecord_PR_nodeID,	/* Member nodeID is present */
	SGSNSMORecord_PR_localSequenceNumber,	/* Member localSequenceNumber is present */
} SGSNSMORecord_PR;

/* Forward declarations */
struct Diagnostics;
struct ManagementExtensions;

/* SGSNSMORecord */
typedef struct SGSNSMORecord {
	CallEventRecordType_t	 recordType;
	IMSI_t	 servedIMSI;
	IMEI_t	*servedIMEI	/* OPTIONAL */;
	MSISDN_t	*servedMSISDN	/* OPTIONAL */;
	MSNetworkCapability_t	*msNetworkCapability	/* OPTIONAL */;
	AddressString_t	*serviceCentre	/* OPTIONAL */;
	RecordingEntity_t	 recordingEntity;
	LocationAreaCode_t	*locationArea	/* OPTIONAL */;
	RoutingAreaCode_t	*routingArea	/* OPTIONAL */;
	CellId_t	*cellIdentity	/* OPTIONAL */;
	MessageReference_t	*messageReference	/* OPTIONAL */;
	TimeStamp_t	 originationTime;
	struct Diagnostics	*smsResult	/* OPTIONAL */;
	struct ManagementExtensions	*recordExtensions	/* OPTIONAL */;
	NodeID_t	*nodeID	/* OPTIONAL */;
	LocalSequenceNumber_t	*localSequenceNumber	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSGSNSMORecord, SGSNSMORecord_PR_x) */
	unsigned int _presence_map
		[((16+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SGSNSMORecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SGSNSMORecord;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SMSResult.h"
#include "ManagementExtensions.h"

#endif	/* _SGSNSMORecord_H_ */
