/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "CmccGPRSber130"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_SGSNPDPRecord_H_
#define	_SGSNPDPRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CallEventRecordType.h"
#include "NetworkInitiatedPDPContext.h"
#include <BOOLEAN.h>
#include "IMSI.h"
#include "IMEI.h"
#include "MSNetworkCapability.h"
#include "RoutingAreaCode.h"
#include "LocationAreaCode.h"
#include "CellId.h"
#include "ChargingID.h"
#include "GSNAddress.h"
#include "AccessPointNameNI.h"
#include "PDPType.h"
#include "TimeStamp.h"
#include "CallDuration.h"
#include "SGSNChange.h"
#include "CauseForRecClosing.h"
#include "NodeID.h"
#include "APNSelectionMode.h"
#include "AccessPointNameOI.h"
#include "ListOfTrafficVolumesC.h"
#include "CallDurationC.h"
#include "MSISDN.h"
#include "ConsolidationResult.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SGSNPDPRecord_PR {
	SGSNPDPRecord_PR_recordType,	/* Member recordType is present */
	SGSNPDPRecord_PR_networkInitiation,	/* Member networkInitiation is present */
	SGSNPDPRecord_PR_anonymousAccessIndicator,	/* Member anonymousAccessIndicator is present */
	SGSNPDPRecord_PR_servedIMSI,	/* Member servedIMSI is present */
	SGSNPDPRecord_PR_servedIMEI,	/* Member servedIMEI is present */
	SGSNPDPRecord_PR_sgsnAddress,	/* Member sgsnAddress is present */
	SGSNPDPRecord_PR_msNetworkCapability,	/* Member msNetworkCapability is present */
	SGSNPDPRecord_PR_routingArea,	/* Member routingArea is present */
	SGSNPDPRecord_PR_locationAreaCode,	/* Member locationAreaCode is present */
	SGSNPDPRecord_PR_cellIdentity,	/* Member cellIdentity is present */
	SGSNPDPRecord_PR_chargingID,	/* Member chargingID is present */
	SGSNPDPRecord_PR_ggsnAddressUsed,	/* Member ggsnAddressUsed is present */
	SGSNPDPRecord_PR_accessPointNameNI,	/* Member accessPointNameNI is present */
	SGSNPDPRecord_PR_pdpType,	/* Member pdpType is present */
	SGSNPDPRecord_PR_servedPDPAddress,	/* Member servedPDPAddress is present */
	SGSNPDPRecord_PR_listOfTrafficVolumes,	/* Member listOfTrafficVolumes is present */
	SGSNPDPRecord_PR_recordOpeningTime,	/* Member recordOpeningTime is present */
	SGSNPDPRecord_PR_duration,	/* Member duration is present */
	SGSNPDPRecord_PR_sgsnChange,	/* Member sgsnChange is present */
	SGSNPDPRecord_PR_causeForRecClosing,	/* Member causeForRecClosing is present */
	SGSNPDPRecord_PR_recordSequenceNumber,	/* Member recordSequenceNumber is present */
	SGSNPDPRecord_PR_nodeID,	/* Member nodeID is present */
	SGSNPDPRecord_PR_recordExtensions,	/* Member recordExtensions is present */
	SGSNPDPRecord_PR_apnSelectionMode,	/* Member apnSelectionMode is present */
	SGSNPDPRecord_PR_accessPointNameOI,	/* Member accessPointNameOI is present */
	SGSNPDPRecord_PR_listOfTrafficVolumesC,	/* Member listOfTrafficVolumesC is present */
	SGSNPDPRecord_PR_durationC,	/* Member durationC is present */
	SGSNPDPRecord_PR_servedMSISDN,	/* Member servedMSISDN is present */
	SGSNPDPRecord_PR_consolidationResult,	/* Member consolidationResult is present */
} SGSNPDPRecord_PR;

/* Forward declarations */
struct PDPAddress;
struct ManagementExtensions;
struct IPAddress;
struct ChangeOfCharCondition;
struct RECORDSequenceNumber;

/* SGSNPDPRecord */
typedef struct SGSNPDPRecord {
	CallEventRecordType_t	 recordType;
	NetworkInitiatedPDPContext_t	*networkInitiation	/* OPTIONAL */;
	BOOLEAN_t	*anonymousAccessIndicator	/* OPTIONAL */;
	IMSI_t	 servedIMSI;
	IMEI_t	*servedIMEI	/* OPTIONAL */;
	struct sgsnAddress {
		A_SEQUENCE_OF(struct IPAddress) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} sgsnAddress;
	MSNetworkCapability_t	*msNetworkCapability	/* OPTIONAL */;
	RoutingAreaCode_t	*routingArea	/* OPTIONAL */;
	LocationAreaCode_t	*locationAreaCode	/* OPTIONAL */;
	CellId_t	*cellIdentity	/* OPTIONAL */;
	ChargingID_t	 chargingID;
	GSNAddress_t	 ggsnAddressUsed;
	AccessPointNameNI_t	 accessPointNameNI;
	PDPType_t	 pdpType;
	struct PDPAddress	*servedPDPAddress	/* OPTIONAL */;
	struct listOfTrafficVolumes {
		A_SEQUENCE_OF(struct ChangeOfCharCondition) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} listOfTrafficVolumes;
	TimeStamp_t	 recordOpeningTime;
	CallDuration_t	 duration;
	SGSNChange_t	*sgsnChange	/* OPTIONAL */;
	CauseForRecClosing_t	 causeForRecClosing;
	struct recordSequenceNumber {
		A_SEQUENCE_OF(struct RECORDSequenceNumber) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *recordSequenceNumber;
	NodeID_t	*nodeID	/* OPTIONAL */;
	struct ManagementExtensions	*recordExtensions	/* OPTIONAL */;
	APNSelectionMode_t	*apnSelectionMode	/* OPTIONAL */;
	AccessPointNameOI_t	*accessPointNameOI	/* OPTIONAL */;
	ListOfTrafficVolumesC_t	 listOfTrafficVolumesC;
	CallDurationC_t	 durationC;
	MSISDN_t	*servedMSISDN	/* OPTIONAL */;
	ConsolidationResult_t	 consolidationResult;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSGSNPDPRecord, SGSNPDPRecord_PR_x) */
	unsigned int _presence_map
		[((29+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SGSNPDPRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SGSNPDPRecord;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDPAddress.h"
#include "ManagementExtensions.h"
#include "GSNAddress.h"
#include "ChangeOfCharCondition.h"
#include "RECORDSequenceNumber.h"

#endif	/* _SGSNPDPRecord_H_ */
