
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace CmccGPRSber130.asn {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "APNSelectionMode")]
    public class APNSelectionMode : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "mSorNetworkProvidedSubscriptionVerified", HasTag = true , Tag = 0 )]
            mSorNetworkProvidedSubscriptionVerified , 
            [ASN1EnumItem ( Name = "mSProvidedSubscriptionNotVerified", HasTag = true , Tag = 1 )]
            mSProvidedSubscriptionNotVerified , 
            [ASN1EnumItem ( Name = "networkProvidedSubscriptionNotVerified", HasTag = true , Tag = 2 )]
            networkProvidedSubscriptionNotVerified , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }        

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(APNSelectionMode));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
    }
            
}
