
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace CmccGPRSber130.asn {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "CallEventRecordType")]
    public class CallEventRecordType : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "sgsnPDPRecord", HasTag = true , Tag = 18 )]
            sgsnPDPRecord , 
            [ASN1EnumItem ( Name = "ggsnPDPRecord", HasTag = true , Tag = 19 )]
            ggsnPDPRecord , 
            [ASN1EnumItem ( Name = "sgsnMMRecord", HasTag = true , Tag = 20 )]
            sgsnMMRecord , 
            [ASN1EnumItem ( Name = "sgsnSMORecord", HasTag = true , Tag = 21 )]
            sgsnSMORecord , 
            [ASN1EnumItem ( Name = "sgsnSMTRecord", HasTag = true , Tag = 22 )]
            sgsnSMTRecord , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }        

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CallEventRecordType));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
    }
            
}
