
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace CmccGPRSber130.asn {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "ChangeCondition")]
    public class ChangeCondition : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "qoSChange", HasTag = true , Tag = 0 )]
            qoSChange , 
            [ASN1EnumItem ( Name = "tariffTime", HasTag = true , Tag = 1 )]
            tariffTime , 
            [ASN1EnumItem ( Name = "recordClosure", HasTag = true , Tag = 2 )]
            recordClosure , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }        

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ChangeCondition));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
    }
            
}
