
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace CmccGPRSber130.asn {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "ChangeOfCharConditionC", IsSet = false  )]
    public class ChangeOfCharConditionC : IASN1PreparedElement {
                    
	private DataVolumeGPRS dataVolumeGPRSUplink_ ;
	
        [ASN1Element ( Name = "dataVolumeGPRSUplink", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public DataVolumeGPRS DataVolumeGPRSUplink
        {
            get { return dataVolumeGPRSUplink_; }
            set { dataVolumeGPRSUplink_ = value;  }
        }
        
                
          
	private DataVolumeGPRS dataVolumeGPRSDownlink_ ;
	
        [ASN1Element ( Name = "dataVolumeGPRSDownlink", IsOptional =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public DataVolumeGPRS DataVolumeGPRSDownlink
        {
            get { return dataVolumeGPRSDownlink_; }
            set { dataVolumeGPRSDownlink_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ChangeOfCharConditionC));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
