
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace CmccGPRSber130.asn {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "QoSInformation", IsSet = false  )]
    public class QoSInformation : IASN1PreparedElement {
                    
	private QoSReliability reliability_ ;
	
        [ASN1Element ( Name = "reliability", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public QoSReliability Reliability
        {
            get { return reliability_; }
            set { reliability_ = value;  }
        }
        
                
          
	private QoSDelay delay_ ;
	
        [ASN1Element ( Name = "delay", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public QoSDelay Delay
        {
            get { return delay_; }
            set { delay_ = value;  }
        }
        
                
          
	private QoSPrecedence precedence_ ;
	
        [ASN1Element ( Name = "precedence", IsOptional =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public QoSPrecedence Precedence
        {
            get { return precedence_; }
            set { precedence_ = value;  }
        }
        
                
          
	private QoSPeakThroughput peakThroughput_ ;
	
        [ASN1Element ( Name = "peakThroughput", IsOptional =  false , HasTag =  true, Tag = 3 , HasDefaultValue =  false )  ]
    
        public QoSPeakThroughput PeakThroughput
        {
            get { return peakThroughput_; }
            set { peakThroughput_ = value;  }
        }
        
                
          
	private QoSMeanThroughput meanThroughput_ ;
	
        [ASN1Element ( Name = "meanThroughput", IsOptional =  false , HasTag =  true, Tag = 4 , HasDefaultValue =  false )  ]
    
        public QoSMeanThroughput MeanThroughput
        {
            get { return meanThroughput_; }
            set { meanThroughput_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(QoSInformation));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
