
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace CmccGPRSber130.asn {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "SGSNSMORecord", IsSet = true  )]
    public class SGSNSMORecord : IASN1PreparedElement {
                    
	private CallEventRecordType recordType_ ;
	
        [ASN1Element ( Name = "recordType", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public CallEventRecordType RecordType
        {
            get { return recordType_; }
            set { recordType_ = value;  }
        }
        
                
          
	private IMSI servedIMSI_ ;
	
        [ASN1Element ( Name = "servedIMSI", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public IMSI ServedIMSI
        {
            get { return servedIMSI_; }
            set { servedIMSI_ = value;  }
        }
        
                
          
	private IMEI servedIMEI_ ;
	
        private bool  servedIMEI_present = false ;
	
        [ASN1Element ( Name = "servedIMEI", IsOptional =  true , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public IMEI ServedIMEI
        {
            get { return servedIMEI_; }
            set { servedIMEI_ = value; servedIMEI_present = true;  }
        }
        
                
          
	private MSISDN servedMSISDN_ ;
	
        private bool  servedMSISDN_present = false ;
	
        [ASN1Element ( Name = "servedMSISDN", IsOptional =  true , HasTag =  true, Tag = 3 , HasDefaultValue =  false )  ]
    
        public MSISDN ServedMSISDN
        {
            get { return servedMSISDN_; }
            set { servedMSISDN_ = value; servedMSISDN_present = true;  }
        }
        
                
          
	private MSNetworkCapability msNetworkCapability_ ;
	
        private bool  msNetworkCapability_present = false ;
	
        [ASN1Element ( Name = "msNetworkCapability", IsOptional =  true , HasTag =  true, Tag = 4 , HasDefaultValue =  false )  ]
    
        public MSNetworkCapability MsNetworkCapability
        {
            get { return msNetworkCapability_; }
            set { msNetworkCapability_ = value; msNetworkCapability_present = true;  }
        }
        
                
          
	private AddressString serviceCentre_ ;
	
        private bool  serviceCentre_present = false ;
	
        [ASN1Element ( Name = "serviceCentre", IsOptional =  true , HasTag =  true, Tag = 5 , HasDefaultValue =  false )  ]
    
        public AddressString ServiceCentre
        {
            get { return serviceCentre_; }
            set { serviceCentre_ = value; serviceCentre_present = true;  }
        }
        
                
          
	private RecordingEntity recordingEntity_ ;
	
        [ASN1Element ( Name = "recordingEntity", IsOptional =  false , HasTag =  true, Tag = 6 , HasDefaultValue =  false )  ]
    
        public RecordingEntity RecordingEntity
        {
            get { return recordingEntity_; }
            set { recordingEntity_ = value;  }
        }
        
                
          
	private LocationAreaCode locationArea_ ;
	
        private bool  locationArea_present = false ;
	
        [ASN1Element ( Name = "locationArea", IsOptional =  true , HasTag =  true, Tag = 7 , HasDefaultValue =  false )  ]
    
        public LocationAreaCode LocationArea
        {
            get { return locationArea_; }
            set { locationArea_ = value; locationArea_present = true;  }
        }
        
                
          
	private RoutingAreaCode routingArea_ ;
	
        private bool  routingArea_present = false ;
	
        [ASN1Element ( Name = "routingArea", IsOptional =  true , HasTag =  true, Tag = 8 , HasDefaultValue =  false )  ]
    
        public RoutingAreaCode RoutingArea
        {
            get { return routingArea_; }
            set { routingArea_ = value; routingArea_present = true;  }
        }
        
                
          
	private CellId cellIdentity_ ;
	
        private bool  cellIdentity_present = false ;
	
        [ASN1Element ( Name = "cellIdentity", IsOptional =  true , HasTag =  true, Tag = 9 , HasDefaultValue =  false )  ]
    
        public CellId CellIdentity
        {
            get { return cellIdentity_; }
            set { cellIdentity_ = value; cellIdentity_present = true;  }
        }
        
                
          
	private MessageReference messageReference_ ;
	
        private bool  messageReference_present = false ;
	
        [ASN1Element ( Name = "messageReference", IsOptional =  true , HasTag =  true, Tag = 10 , HasDefaultValue =  false )  ]
    
        public MessageReference MessageReference
        {
            get { return messageReference_; }
            set { messageReference_ = value; messageReference_present = true;  }
        }
        
                
          
	private TimeStamp originationTime_ ;
	
        [ASN1Element ( Name = "originationTime", IsOptional =  false , HasTag =  true, Tag = 11 , HasDefaultValue =  false )  ]
    
        public TimeStamp OriginationTime
        {
            get { return originationTime_; }
            set { originationTime_ = value;  }
        }
        
                
          
	private SMSResult smsResult_ ;
	
        private bool  smsResult_present = false ;
	
        [ASN1Element ( Name = "smsResult", IsOptional =  true , HasTag =  true, Tag = 12, IsImplicitTag = false  , HasDefaultValue =  false )  ]
    
        public SMSResult SmsResult
        {
            get { return smsResult_; }
            set { smsResult_ = value; smsResult_present = true;  }
        }
        
                
          
	private ManagementExtensions recordExtensions_ ;
	
        private bool  recordExtensions_present = false ;
	
        [ASN1Element ( Name = "recordExtensions", IsOptional =  true , HasTag =  true, Tag = 13 , HasDefaultValue =  false )  ]
    
        public ManagementExtensions RecordExtensions
        {
            get { return recordExtensions_; }
            set { recordExtensions_ = value; recordExtensions_present = true;  }
        }
        
                
          
	private NodeID nodeID_ ;
	
        private bool  nodeID_present = false ;
	
        [ASN1Element ( Name = "nodeID", IsOptional =  true , HasTag =  true, Tag = 14 , HasDefaultValue =  false )  ]
    
        public NodeID NodeID
        {
            get { return nodeID_; }
            set { nodeID_ = value; nodeID_present = true;  }
        }
        
                
          
	private LocalSequenceNumber localSequenceNumber_ ;
	
        private bool  localSequenceNumber_present = false ;
	
        [ASN1Element ( Name = "localSequenceNumber", IsOptional =  true , HasTag =  true, Tag = 15 , HasDefaultValue =  false )  ]
    
        public LocalSequenceNumber LocalSequenceNumber
        {
            get { return localSequenceNumber_; }
            set { localSequenceNumber_ = value; localSequenceNumber_present = true;  }
        }
        
                
  
        public bool isServedIMEIPresent () {
            return this.servedIMEI_present == true;
        }
        
        public bool isServedMSISDNPresent () {
            return this.servedMSISDN_present == true;
        }
        
        public bool isMsNetworkCapabilityPresent () {
            return this.msNetworkCapability_present == true;
        }
        
        public bool isServiceCentrePresent () {
            return this.serviceCentre_present == true;
        }
        
        public bool isLocationAreaPresent () {
            return this.locationArea_present == true;
        }
        
        public bool isRoutingAreaPresent () {
            return this.routingArea_present == true;
        }
        
        public bool isCellIdentityPresent () {
            return this.cellIdentity_present == true;
        }
        
        public bool isMessageReferencePresent () {
            return this.messageReference_present == true;
        }
        
        public bool isSmsResultPresent () {
            return this.smsResult_present == true;
        }
        
        public bool isRecordExtensionsPresent () {
            return this.recordExtensions_present == true;
        }
        
        public bool isNodeIDPresent () {
            return this.nodeID_present == true;
        }
        
        public bool isLocalSequenceNumberPresent () {
            return this.localSequenceNumber_present == true;
        }
        

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SGSNSMORecord));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
