
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace CmccGPRSber130.asn {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "SGSNPDPRecord", IsSet = true  )]
    public class SGSNPDPRecord : IASN1PreparedElement {
                    
	private CallEventRecordType recordType_ ;
	
        [ASN1Element ( Name = "recordType", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public CallEventRecordType RecordType
        {
            get { return recordType_; }
            set { recordType_ = value;  }
        }
        
                
          
	private NetworkInitiatedPDPContext networkInitiation_ ;
	
        private bool  networkInitiation_present = false ;
	
        [ASN1Element ( Name = "networkInitiation", IsOptional =  true , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public NetworkInitiatedPDPContext NetworkInitiation
        {
            get { return networkInitiation_; }
            set { networkInitiation_ = value; networkInitiation_present = true;  }
        }
        
                
          
	private bool anonymousAccessIndicator_ ;
	
        private bool  anonymousAccessIndicator_present = false ;
	[ASN1Boolean( Name = "" )]
    
        [ASN1Element ( Name = "anonymousAccessIndicator", IsOptional =  true , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public bool AnonymousAccessIndicator
        {
            get { return anonymousAccessIndicator_; }
            set { anonymousAccessIndicator_ = value; anonymousAccessIndicator_present = true;  }
        }
        
                
          
	private IMSI servedIMSI_ ;
	
        [ASN1Element ( Name = "servedIMSI", IsOptional =  false , HasTag =  true, Tag = 3 , HasDefaultValue =  false )  ]
    
        public IMSI ServedIMSI
        {
            get { return servedIMSI_; }
            set { servedIMSI_ = value;  }
        }
        
                
          
	private IMEI servedIMEI_ ;
	
        private bool  servedIMEI_present = false ;
	
        [ASN1Element ( Name = "servedIMEI", IsOptional =  true , HasTag =  true, Tag = 4 , HasDefaultValue =  false )  ]
    
        public IMEI ServedIMEI
        {
            get { return servedIMEI_; }
            set { servedIMEI_ = value; servedIMEI_present = true;  }
        }
        
                
          
	private System.Collections.Generic.ICollection<GSNAddress> sgsnAddress_ ;
	
[ASN1SequenceOf( Name = "", IsSetOf = false  )]

    
        [ASN1Element ( Name = "sgsnAddress", IsOptional =  false , HasTag =  true, Tag = 5, IsImplicitTag = false  , HasDefaultValue =  false )  ]
    
        public System.Collections.Generic.ICollection<GSNAddress> SgsnAddress
        {
            get { return sgsnAddress_; }
            set { sgsnAddress_ = value;  }
        }
        
                
          
	private MSNetworkCapability msNetworkCapability_ ;
	
        private bool  msNetworkCapability_present = false ;
	
        [ASN1Element ( Name = "msNetworkCapability", IsOptional =  true , HasTag =  true, Tag = 6 , HasDefaultValue =  false )  ]
    
        public MSNetworkCapability MsNetworkCapability
        {
            get { return msNetworkCapability_; }
            set { msNetworkCapability_ = value; msNetworkCapability_present = true;  }
        }
        
                
          
	private RoutingAreaCode routingArea_ ;
	
        private bool  routingArea_present = false ;
	
        [ASN1Element ( Name = "routingArea", IsOptional =  true , HasTag =  true, Tag = 7 , HasDefaultValue =  false )  ]
    
        public RoutingAreaCode RoutingArea
        {
            get { return routingArea_; }
            set { routingArea_ = value; routingArea_present = true;  }
        }
        
                
          
	private LocationAreaCode locationAreaCode_ ;
	
        private bool  locationAreaCode_present = false ;
	
        [ASN1Element ( Name = "locationAreaCode", IsOptional =  true , HasTag =  true, Tag = 8 , HasDefaultValue =  false )  ]
    
        public LocationAreaCode LocationAreaCode
        {
            get { return locationAreaCode_; }
            set { locationAreaCode_ = value; locationAreaCode_present = true;  }
        }
        
                
          
	private CellId cellIdentity_ ;
	
        private bool  cellIdentity_present = false ;
	
        [ASN1Element ( Name = "cellIdentity", IsOptional =  true , HasTag =  true, Tag = 9 , HasDefaultValue =  false )  ]
    
        public CellId CellIdentity
        {
            get { return cellIdentity_; }
            set { cellIdentity_ = value; cellIdentity_present = true;  }
        }
        
                
          
	private ChargingID chargingID_ ;
	
        [ASN1Element ( Name = "chargingID", IsOptional =  false , HasTag =  true, Tag = 10 , HasDefaultValue =  false )  ]
    
        public ChargingID ChargingID
        {
            get { return chargingID_; }
            set { chargingID_ = value;  }
        }
        
                
          
	private GSNAddress ggsnAddressUsed_ ;
	
        [ASN1Element ( Name = "ggsnAddressUsed", IsOptional =  false , HasTag =  true, Tag = 11, IsImplicitTag = false  , HasDefaultValue =  false )  ]
    
        public GSNAddress GgsnAddressUsed
        {
            get { return ggsnAddressUsed_; }
            set { ggsnAddressUsed_ = value;  }
        }
        
                
          
	private AccessPointNameNI accessPointNameNI_ ;
	
        [ASN1Element ( Name = "accessPointNameNI", IsOptional =  false , HasTag =  true, Tag = 12 , HasDefaultValue =  false )  ]
    
        public AccessPointNameNI AccessPointNameNI
        {
            get { return accessPointNameNI_; }
            set { accessPointNameNI_ = value;  }
        }
        
                
          
	private PDPType pdpType_ ;
	
        [ASN1Element ( Name = "pdpType", IsOptional =  false , HasTag =  true, Tag = 13 , HasDefaultValue =  false )  ]
    
        public PDPType PdpType
        {
            get { return pdpType_; }
            set { pdpType_ = value;  }
        }
        
                
          
	private PDPAddress servedPDPAddress_ ;
	
        private bool  servedPDPAddress_present = false ;
	
        [ASN1Element ( Name = "servedPDPAddress", IsOptional =  true , HasTag =  true, Tag = 14, IsImplicitTag = false  , HasDefaultValue =  false )  ]
    
        public PDPAddress ServedPDPAddress
        {
            get { return servedPDPAddress_; }
            set { servedPDPAddress_ = value; servedPDPAddress_present = true;  }
        }
        
                
          
	private System.Collections.Generic.ICollection<ChangeOfCharCondition> listOfTrafficVolumes_ ;
	
[ASN1SequenceOf( Name = "", IsSetOf = false  )]

    
        [ASN1Element ( Name = "listOfTrafficVolumes", IsOptional =  false , HasTag =  true, Tag = 15 , HasDefaultValue =  false )  ]
    
        public System.Collections.Generic.ICollection<ChangeOfCharCondition> ListOfTrafficVolumes
        {
            get { return listOfTrafficVolumes_; }
            set { listOfTrafficVolumes_ = value;  }
        }
        
                
          
	private TimeStamp recordOpeningTime_ ;
	
        [ASN1Element ( Name = "recordOpeningTime", IsOptional =  false , HasTag =  true, Tag = 16 , HasDefaultValue =  false )  ]
    
        public TimeStamp RecordOpeningTime
        {
            get { return recordOpeningTime_; }
            set { recordOpeningTime_ = value;  }
        }
        
                
          
	private CallDuration duration_ ;
	
        [ASN1Element ( Name = "duration", IsOptional =  false , HasTag =  true, Tag = 17 , HasDefaultValue =  false )  ]
    
        public CallDuration Duration
        {
            get { return duration_; }
            set { duration_ = value;  }
        }
        
                
          
	private SGSNChange sgsnChange_ ;
	
        private bool  sgsnChange_present = false ;
	
        [ASN1Element ( Name = "sgsnChange", IsOptional =  true , HasTag =  true, Tag = 18 , HasDefaultValue =  false )  ]
    
        public SGSNChange SgsnChange
        {
            get { return sgsnChange_; }
            set { sgsnChange_ = value; sgsnChange_present = true;  }
        }
        
                
          
	private CauseForRecClosing causeForRecClosing_ ;
	
        [ASN1Element ( Name = "causeForRecClosing", IsOptional =  false , HasTag =  true, Tag = 19 , HasDefaultValue =  false )  ]
    
        public CauseForRecClosing CauseForRecClosing
        {
            get { return causeForRecClosing_; }
            set { causeForRecClosing_ = value;  }
        }
        
                
          
	private System.Collections.Generic.ICollection<RECORDSequenceNumber> recordSequenceNumber_ ;
	
        private bool  recordSequenceNumber_present = false ;
	
[ASN1SequenceOf( Name = "", IsSetOf = false  )]

    
        [ASN1Element ( Name = "recordSequenceNumber", IsOptional =  true , HasTag =  true, Tag = 21 , HasDefaultValue =  false )  ]
    
        public System.Collections.Generic.ICollection<RECORDSequenceNumber> RecordSequenceNumber
        {
            get { return recordSequenceNumber_; }
            set { recordSequenceNumber_ = value; recordSequenceNumber_present = true;  }
        }
        
                
          
	private NodeID nodeID_ ;
	
        private bool  nodeID_present = false ;
	
        [ASN1Element ( Name = "nodeID", IsOptional =  true , HasTag =  true, Tag = 22 , HasDefaultValue =  false )  ]
    
        public NodeID NodeID
        {
            get { return nodeID_; }
            set { nodeID_ = value; nodeID_present = true;  }
        }
        
                
          
	private ManagementExtensions recordExtensions_ ;
	
        private bool  recordExtensions_present = false ;
	
        [ASN1Element ( Name = "recordExtensions", IsOptional =  true , HasTag =  true, Tag = 23 , HasDefaultValue =  false )  ]
    
        public ManagementExtensions RecordExtensions
        {
            get { return recordExtensions_; }
            set { recordExtensions_ = value; recordExtensions_present = true;  }
        }
        
                
          
	private APNSelectionMode apnSelectionMode_ ;
	
        private bool  apnSelectionMode_present = false ;
	
        [ASN1Element ( Name = "apnSelectionMode", IsOptional =  true , HasTag =  true, Tag = 25 , HasDefaultValue =  false )  ]
    
        public APNSelectionMode ApnSelectionMode
        {
            get { return apnSelectionMode_; }
            set { apnSelectionMode_ = value; apnSelectionMode_present = true;  }
        }
        
                
          
	private AccessPointNameOI accessPointNameOI_ ;
	
        private bool  accessPointNameOI_present = false ;
	
        [ASN1Element ( Name = "accessPointNameOI", IsOptional =  true , HasTag =  true, Tag = 26 , HasDefaultValue =  false )  ]
    
        public AccessPointNameOI AccessPointNameOI
        {
            get { return accessPointNameOI_; }
            set { accessPointNameOI_ = value; accessPointNameOI_present = true;  }
        }
        
                
          
	private ListOfTrafficVolumesC listOfTrafficVolumesC_ ;
	
        [ASN1Element ( Name = "listOfTrafficVolumesC", IsOptional =  false , HasTag =  true, Tag = 27 , HasDefaultValue =  false )  ]
    
        public ListOfTrafficVolumesC ListOfTrafficVolumesC
        {
            get { return listOfTrafficVolumesC_; }
            set { listOfTrafficVolumesC_ = value;  }
        }
        
                
          
	private CallDurationC durationC_ ;
	
        [ASN1Element ( Name = "durationC", IsOptional =  false , HasTag =  true, Tag = 28 , HasDefaultValue =  false )  ]
    
        public CallDurationC DurationC
        {
            get { return durationC_; }
            set { durationC_ = value;  }
        }
        
                
          
	private MSISDN servedMSISDN_ ;
	
        private bool  servedMSISDN_present = false ;
	
        [ASN1Element ( Name = "servedMSISDN", IsOptional =  true , HasTag =  true, Tag = 29 , HasDefaultValue =  false )  ]
    
        public MSISDN ServedMSISDN
        {
            get { return servedMSISDN_; }
            set { servedMSISDN_ = value; servedMSISDN_present = true;  }
        }
        
                
          
	private ConsolidationResult consolidationResult_ ;
	
        [ASN1Element ( Name = "consolidationResult", IsOptional =  false , HasTag =  true, Tag = 30 , HasDefaultValue =  false )  ]
    
        public ConsolidationResult ConsolidationResult
        {
            get { return consolidationResult_; }
            set { consolidationResult_ = value;  }
        }
        
                
  
        public bool isNetworkInitiationPresent () {
            return this.networkInitiation_present == true;
        }
        
        public bool isAnonymousAccessIndicatorPresent () {
            return this.anonymousAccessIndicator_present == true;
        }
        
        public bool isServedIMEIPresent () {
            return this.servedIMEI_present == true;
        }
        
        public bool isMsNetworkCapabilityPresent () {
            return this.msNetworkCapability_present == true;
        }
        
        public bool isRoutingAreaPresent () {
            return this.routingArea_present == true;
        }
        
        public bool isLocationAreaCodePresent () {
            return this.locationAreaCode_present == true;
        }
        
        public bool isCellIdentityPresent () {
            return this.cellIdentity_present == true;
        }
        
        public bool isServedPDPAddressPresent () {
            return this.servedPDPAddress_present == true;
        }
        
        public bool isSgsnChangePresent () {
            return this.sgsnChange_present == true;
        }
        
        public bool isRecordSequenceNumberPresent () {
            return this.recordSequenceNumber_present == true;
        }
        
        public bool isNodeIDPresent () {
            return this.nodeID_present == true;
        }
        
        public bool isRecordExtensionsPresent () {
            return this.recordExtensions_present == true;
        }
        
        public bool isApnSelectionModePresent () {
            return this.apnSelectionMode_present == true;
        }
        
        public bool isAccessPointNameOIPresent () {
            return this.accessPointNameOI_present == true;
        }
        
        public bool isServedMSISDNPresent () {
            return this.servedMSISDN_present == true;
        }
        

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(SGSNPDPRecord));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
