/* Do not modify this file.                                                   */
/* It is created automatically by the ASN.1 to Wireshark dissector compiler   */
/* packet-CmccGPRSber130-hfarr.c                                              */
/* F:/bin/trunk-1.4/tools/asn2wrs.py G:/xmlconvertsql/ICDR_EDGE/ICDR_EDGE/bin/Debug/asn1/CmccGPRSber130.asn1 */


/* --- Module CmccGPRSber130 --- --- ---                                      */

    { &hf_CmccGPRSber130_sgsnPDPRecord,
      { "sgsnPDPRecord", "CmccGPRSber130.sgsnPDPRecord",
        FT_NONE, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_ggsnPDPRecord,
      { "ggsnPDPRecord", "CmccGPRSber130.ggsnPDPRecord",
        FT_NONE, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_sgsnMMRecord,
      { "sgsnMMRecord", "CmccGPRSber130.sgsnMMRecord",
        FT_NONE, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_sgsnSMORecord,
      { "sgsnSMORecord", "CmccGPRSber130.sgsnSMORecord",
        FT_NONE, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_sgsnSMTRecord,
      { "sgsnSMTRecord", "CmccGPRSber130.sgsnSMTRecord",
        FT_NONE, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_recordType,
      { "recordType", "CmccGPRSber130.recordType",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_CallEventRecordType_vals), 0,
        "CallEventRecordType", HFILL }},
    { &hf_CmccGPRSber130_networkInitiation,
      { "networkInitiation", "CmccGPRSber130.networkInitiation",
        FT_BOOLEAN, BASE_NONE, NULL, 0,
        "NetworkInitiatedPDPContext", HFILL }},
    { &hf_CmccGPRSber130_anonymousAccessIndicator,
      { "anonymousAccessIndicator", "CmccGPRSber130.anonymousAccessIndicator",
        FT_BOOLEAN, BASE_NONE, NULL, 0,
        "BOOLEAN", HFILL }},
    { &hf_CmccGPRSber130_servedIMSI,
      { "servedIMSI", "CmccGPRSber130.servedIMSI",
        FT_BYTES, BASE_NONE, NULL, 0,
        "IMSI", HFILL }},
    { &hf_CmccGPRSber130_ggsnAddress,
      { "ggsnAddress", "CmccGPRSber130.ggsnAddress",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_IPAddress_vals), 0,
        "GSNAddress", HFILL }},
    { &hf_CmccGPRSber130_chargingID,
      { "chargingID", "CmccGPRSber130.chargingID",
        FT_UINT32, BASE_DEC, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_sgsnAddress,
      { "sgsnAddress", "CmccGPRSber130.sgsnAddress",
        FT_UINT32, BASE_DEC, NULL, 0,
        "SEQUENCE_OF_GSNAddress", HFILL }},
    { &hf_CmccGPRSber130_sgsnAddress_item,
      { "GSNAddress", "CmccGPRSber130.GSNAddress",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_IPAddress_vals), 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_accessPointNameNI,
      { "accessPointNameNI", "CmccGPRSber130.accessPointNameNI",
        FT_BYTES, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_pdpType,
      { "pdpType", "CmccGPRSber130.pdpType",
        FT_BYTES, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_servedPDPAddress,
      { "servedPDPAddress", "CmccGPRSber130.servedPDPAddress",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_PDPAddress_vals), 0,
        "PDPAddress", HFILL }},
    { &hf_CmccGPRSber130_remotePDPAddress,
      { "remotePDPAddress", "CmccGPRSber130.remotePDPAddress",
        FT_UINT32, BASE_DEC, NULL, 0,
        "SEQUENCE_OF_PDPAddress", HFILL }},
    { &hf_CmccGPRSber130_remotePDPAddress_item,
      { "PDPAddress", "CmccGPRSber130.PDPAddress",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_PDPAddress_vals), 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_dynamicAddressFlag,
      { "dynamicAddressFlag", "CmccGPRSber130.dynamicAddressFlag",
        FT_BOOLEAN, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_listOfTrafficVolumes,
      { "listOfTrafficVolumes", "CmccGPRSber130.listOfTrafficVolumes",
        FT_UINT32, BASE_DEC, NULL, 0,
        "SEQUENCE_OF_ChangeOfCharCondition", HFILL }},
    { &hf_CmccGPRSber130_listOfTrafficVolumes_item,
      { "ChangeOfCharCondition", "CmccGPRSber130.ChangeOfCharCondition",
        FT_NONE, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_recordOpeningTime,
      { "recordOpeningTime", "CmccGPRSber130.recordOpeningTime",
        FT_BYTES, BASE_NONE, NULL, 0,
        "TimeStamp", HFILL }},
    { &hf_CmccGPRSber130_duration,
      { "duration", "CmccGPRSber130.duration",
        FT_INT32, BASE_DEC, NULL, 0,
        "INTEGER", HFILL }},
    { &hf_CmccGPRSber130_causeForRecClosing,
      { "causeForRecClosing", "CmccGPRSber130.causeForRecClosing",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_CauseForRecClosing_vals), 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_recordSequenceNumber,
      { "recordSequenceNumber", "CmccGPRSber130.recordSequenceNumber",
        FT_NONE, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_nodeID,
      { "nodeID", "CmccGPRSber130.nodeID",
        FT_BYTES, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_recordExtensions,
      { "recordExtensions", "CmccGPRSber130.recordExtensions",
        FT_UINT32, BASE_DEC, NULL, 0,
        "ManagementExtensions", HFILL }},
    { &hf_CmccGPRSber130_apnSelectionMode,
      { "apnSelectionMode", "CmccGPRSber130.apnSelectionMode",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_APNSelectionMode_vals), 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_listOfTrafficVolumesC,
      { "listOfTrafficVolumesC", "CmccGPRSber130.listOfTrafficVolumesC",
        FT_NONE, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_durationC,
      { "durationC", "CmccGPRSber130.durationC",
        FT_NONE, BASE_NONE, NULL, 0,
        "CallDurationC", HFILL }},
    { &hf_CmccGPRSber130_servedMSISDN,
      { "servedMSISDN", "CmccGPRSber130.servedMSISDN",
        FT_BYTES, BASE_NONE, NULL, 0,
        "MSISDN", HFILL }},
    { &hf_CmccGPRSber130_consolidationResult,
      { "consolidationResult", "CmccGPRSber130.consolidationResult",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_ConsolidationResult_vals), 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_servedIMEI,
      { "servedIMEI", "CmccGPRSber130.servedIMEI",
        FT_BYTES, BASE_NONE, NULL, 0,
        "IMEI", HFILL }},
    { &hf_CmccGPRSber130_sgsnAddress_01,
      { "sgsnAddress", "CmccGPRSber130.sgsnAddress",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_IPAddress_vals), 0,
        "GSNAddress", HFILL }},
    { &hf_CmccGPRSber130_msNetworkCapability,
      { "msNetworkCapability", "CmccGPRSber130.msNetworkCapability",
        FT_BYTES, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_routingArea,
      { "routingArea", "CmccGPRSber130.routingArea",
        FT_BYTES, BASE_NONE, NULL, 0,
        "RoutingAreaCode", HFILL }},
    { &hf_CmccGPRSber130_locationAreaCode,
      { "locationAreaCode", "CmccGPRSber130.locationAreaCode",
        FT_BYTES, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_cellIdentity,
      { "cellIdentity", "CmccGPRSber130.cellIdentity",
        FT_BYTES, BASE_NONE, NULL, 0,
        "CellId", HFILL }},
    { &hf_CmccGPRSber130_changeLocation,
      { "changeLocation", "CmccGPRSber130.changeLocation",
        FT_UINT32, BASE_DEC, NULL, 0,
        "SEQUENCE_OF_ChangeLocation", HFILL }},
    { &hf_CmccGPRSber130_changeLocation_item,
      { "ChangeLocation", "CmccGPRSber130.ChangeLocation",
        FT_NONE, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_duration_01,
      { "duration", "CmccGPRSber130.duration",
        FT_INT32, BASE_DEC, NULL, 0,
        "CallDuration", HFILL }},
    { &hf_CmccGPRSber130_sgsnChange,
      { "sgsnChange", "CmccGPRSber130.sgsnChange",
        FT_BOOLEAN, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_diagnostics,
      { "diagnostics", "CmccGPRSber130.diagnostics",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_Diagnostics_vals), 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_recordSequenceNumber_01,
      { "recordSequenceNumber", "CmccGPRSber130.recordSequenceNumber",
        FT_INT32, BASE_DEC, NULL, 0,
        "INTEGER", HFILL }},
    { &hf_CmccGPRSber130_localSequenceNumber,
      { "localSequenceNumber", "CmccGPRSber130.localSequenceNumber",
        FT_UINT32, BASE_DEC, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_ggsnAddressUsed,
      { "ggsnAddressUsed", "CmccGPRSber130.ggsnAddressUsed",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_IPAddress_vals), 0,
        "GSNAddress", HFILL }},
    { &hf_CmccGPRSber130_recordSequenceNumber_02,
      { "recordSequenceNumber", "CmccGPRSber130.recordSequenceNumber",
        FT_UINT32, BASE_DEC, NULL, 0,
        "SEQUENCE_OF_RECORDSequenceNumber", HFILL }},
    { &hf_CmccGPRSber130_recordSequenceNumber_item,
      { "RECORDSequenceNumber", "CmccGPRSber130.RECORDSequenceNumber",
        FT_NONE, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_accessPointNameOI,
      { "accessPointNameOI", "CmccGPRSber130.accessPointNameOI",
        FT_BYTES, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_serviceCentre,
      { "serviceCentre", "CmccGPRSber130.serviceCentre",
        FT_BYTES, BASE_NONE, NULL, 0,
        "AddressString", HFILL }},
    { &hf_CmccGPRSber130_recordingEntity,
      { "recordingEntity", "CmccGPRSber130.recordingEntity",
        FT_BYTES, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_locationArea,
      { "locationArea", "CmccGPRSber130.locationArea",
        FT_BYTES, BASE_NONE, NULL, 0,
        "LocationAreaCode", HFILL }},
    { &hf_CmccGPRSber130_messageReference,
      { "messageReference", "CmccGPRSber130.messageReference",
        FT_BYTES, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_originationTime,
      { "originationTime", "CmccGPRSber130.originationTime",
        FT_BYTES, BASE_NONE, NULL, 0,
        "TimeStamp", HFILL }},
    { &hf_CmccGPRSber130_smsResult,
      { "smsResult", "CmccGPRSber130.smsResult",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_Diagnostics_vals), 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_peak,
      { "peak", "CmccGPRSber130.peak",
        FT_INT32, BASE_DEC, NULL, 0,
        "INTEGER", HFILL }},
    { &hf_CmccGPRSber130_offPeak,
      { "offPeak", "CmccGPRSber130.offPeak",
        FT_INT32, BASE_DEC, NULL, 0,
        "INTEGER", HFILL }},
    { &hf_CmccGPRSber130_routingAreaCode,
      { "routingAreaCode", "CmccGPRSber130.routingAreaCode",
        FT_BYTES, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_cellId,
      { "cellId", "CmccGPRSber130.cellId",
        FT_BYTES, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_changeTime,
      { "changeTime", "CmccGPRSber130.changeTime",
        FT_BYTES, BASE_NONE, NULL, 0,
        "TimeStamp", HFILL }},
    { &hf_CmccGPRSber130_qosRequested,
      { "qosRequested", "CmccGPRSber130.qosRequested",
        FT_NONE, BASE_NONE, NULL, 0,
        "QoSInformation", HFILL }},
    { &hf_CmccGPRSber130_qosNegotiated,
      { "qosNegotiated", "CmccGPRSber130.qosNegotiated",
        FT_NONE, BASE_NONE, NULL, 0,
        "QoSInformation", HFILL }},
    { &hf_CmccGPRSber130_dataVolumeGPRSUplink,
      { "dataVolumeGPRSUplink", "CmccGPRSber130.dataVolumeGPRSUplink",
        FT_INT32, BASE_DEC, NULL, 0,
        "DataVolumeGPRS", HFILL }},
    { &hf_CmccGPRSber130_dataVolumeGPRSDownlink,
      { "dataVolumeGPRSDownlink", "CmccGPRSber130.dataVolumeGPRSDownlink",
        FT_INT32, BASE_DEC, NULL, 0,
        "DataVolumeGPRS", HFILL }},
    { &hf_CmccGPRSber130_changeCondition,
      { "changeCondition", "CmccGPRSber130.changeCondition",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_ChangeCondition_vals), 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_gsm0408Cause,
      { "gsm0408Cause", "CmccGPRSber130.gsm0408Cause",
        FT_INT32, BASE_DEC, NULL, 0,
        "INTEGER", HFILL }},
    { &hf_CmccGPRSber130_gsm0902MapErrorValue,
      { "gsm0902MapErrorValue", "CmccGPRSber130.gsm0902MapErrorValue",
        FT_INT32, BASE_DEC, NULL, 0,
        "INTEGER", HFILL }},
    { &hf_CmccGPRSber130_ccittQ767Cause,
      { "ccittQ767Cause", "CmccGPRSber130.ccittQ767Cause",
        FT_INT32, BASE_DEC, NULL, 0,
        "INTEGER", HFILL }},
    { &hf_CmccGPRSber130_networkSpecificCause,
      { "networkSpecificCause", "CmccGPRSber130.networkSpecificCause",
        FT_NONE, BASE_NONE, NULL, 0,
        "ManagementExtension", HFILL }},
    { &hf_CmccGPRSber130_manufacturerSpecificCause,
      { "manufacturerSpecificCause", "CmccGPRSber130.manufacturerSpecificCause",
        FT_NONE, BASE_NONE, NULL, 0,
        "ManagementExtension", HFILL }},
    { &hf_CmccGPRSber130_iPBinaryAddress,
      { "iPBinaryAddress", "CmccGPRSber130.iPBinaryAddress",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_IPBinaryAddress_vals), 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_iPTextRepresentedAddress,
      { "iPTextRepresentedAddress", "CmccGPRSber130.iPTextRepresentedAddress",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_IPTextRepresentedAddress_vals), 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_iPBinV4Address,
      { "iPBinV4Address", "CmccGPRSber130.iPBinV4Address",
        FT_BYTES, BASE_NONE, NULL, 0,
        "OCTET_STRING_SIZE_4", HFILL }},
    { &hf_CmccGPRSber130_iPBinV6Address,
      { "iPBinV6Address", "CmccGPRSber130.iPBinV6Address",
        FT_BYTES, BASE_NONE, NULL, 0,
        "OCTET_STRING_SIZE_16", HFILL }},
    { &hf_CmccGPRSber130_iPTextV4Address,
      { "iPTextV4Address", "CmccGPRSber130.iPTextV4Address",
        FT_BYTES, BASE_NONE, NULL, 0,
        "OCTET_STRING_SIZE_7_15", HFILL }},
    { &hf_CmccGPRSber130_iPTextV6Address,
      { "iPTextV6Address", "CmccGPRSber130.iPTextV6Address",
        FT_BYTES, BASE_NONE, NULL, 0,
        "OCTET_STRING_SIZE_15_45", HFILL }},
    { &hf_CmccGPRSber130_peak_01,
      { "peak", "CmccGPRSber130.peak",
        FT_NONE, BASE_NONE, NULL, 0,
        "ChangeOfCharConditionC", HFILL }},
    { &hf_CmccGPRSber130_offPeak_01,
      { "offPeak", "CmccGPRSber130.offPeak",
        FT_NONE, BASE_NONE, NULL, 0,
        "ChangeOfCharConditionC", HFILL }},
    { &hf_CmccGPRSber130_ManagementExtensions_item,
      { "ManagementExtension", "CmccGPRSber130.ManagementExtension",
        FT_NONE, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_iPAddress,
      { "iPAddress", "CmccGPRSber130.iPAddress",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_IPAddress_vals), 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_eTSIAddress,
      { "eTSIAddress", "CmccGPRSber130.eTSIAddress",
        FT_BYTES, BASE_NONE, NULL, 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_reliability,
      { "reliability", "CmccGPRSber130.reliability",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_QoSReliability_vals), 0,
        "QoSReliability", HFILL }},
    { &hf_CmccGPRSber130_delay,
      { "delay", "CmccGPRSber130.delay",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_QoSDelay_vals), 0,
        "QoSDelay", HFILL }},
    { &hf_CmccGPRSber130_precedence,
      { "precedence", "CmccGPRSber130.precedence",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_QoSPrecedence_vals), 0,
        "QoSPrecedence", HFILL }},
    { &hf_CmccGPRSber130_peakThroughput,
      { "peakThroughput", "CmccGPRSber130.peakThroughput",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_QoSPeakThroughput_vals), 0,
        "QoSPeakThroughput", HFILL }},
    { &hf_CmccGPRSber130_meanThroughput,
      { "meanThroughput", "CmccGPRSber130.meanThroughput",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_QoSMeanThroughput_vals), 0,
        "QoSMeanThroughput", HFILL }},
    { &hf_CmccGPRSber130_gsnAddress,
      { "gsnAddress", "CmccGPRSber130.gsnAddress",
        FT_UINT32, BASE_DEC, VALS(CmccGPRSber130_IPAddress_vals), 0,
        NULL, HFILL }},
    { &hf_CmccGPRSber130_recordNumberList,
      { "recordNumberList", "CmccGPRSber130.recordNumberList",
        FT_UINT32, BASE_DEC, NULL, 0,
        "SEQUENCE_OF_RecordNumber", HFILL }},
    { &hf_CmccGPRSber130_recordNumberList_item,
      { "RecordNumber", "CmccGPRSber130.RecordNumber",
        FT_INT32, BASE_DEC, NULL, 0,
        NULL, HFILL }},
