/**
 * InternalXML.cs
 *
 * This file was generated by XMLSpy 2008r2sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */

using System.Xml;
using Altova.TypeInfo;

namespace Altova.Xml
{
	public abstract class InternalXML
	{
		public static string XMLToString( XmlNode xmlTree )
		{
			return XmlTreeOperations.SaveXml( (XmlDocument) xmlTree, false );
		}

		public static byte[] XMLToBase64Binary( XmlNode xmlTree, string encoding, string byteorder, bool bBOM )
		{
			return XmlTreeOperations.SaveXmlBinary( (XmlDocument) xmlTree, encoding, System.String.Compare(byteorder, "big endian", true) == 0, bBOM, false );
		}

		public static XmlDocument XMLFromString( string xmlString )
		{
			return XmlTreeOperations.LoadXml( xmlString );
		}

		public static XmlDocument XMLFromBase64Binary( byte[] xmlString )
		{
			return XmlTreeOperations.LoadXmlBinary( xmlString );
		}

		public static void ThrowException( string exception )
		{
			throw new System.Exception(exception);
		}
	}
}
