
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace GPRSber {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "CauseForRecClosing")]
    public class CauseForRecClosing : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "normalRelease", HasTag = true , Tag = 0 )]
            normalRelease , 
            [ASN1EnumItem ( Name = "abnormalRelease", HasTag = true , Tag = 4 )]
            abnormalRelease , 
            [ASN1EnumItem ( Name = "volumeLimit", HasTag = true , Tag = 16 )]
            volumeLimit , 
            [ASN1EnumItem ( Name = "timeLimit", HasTag = true , Tag = 17 )]
            timeLimit , 
            [ASN1EnumItem ( Name = "sGSNChange", HasTag = true , Tag = 18 )]
            sGSNChange , 
            [ASN1EnumItem ( Name = "maxChangeCond", HasTag = true , Tag = 19 )]
            maxChangeCond , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }        

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CauseForRecClosing));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
    }
            
}
