
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace GPRSber {


    [ASN1PreparedElement]
    [ASN1Choice ( Name = "Diagnostics") ]
    public class Diagnostics : IASN1PreparedElement {
                    
        
	private long gsm0408Cause_ ;
        private bool  gsm0408Cause_selected = false ;
        
        
        
        [ASN1Element ( Name = "gsm0408Cause", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    [ASN1Integer( Name = "" )]
    
        public long Gsm0408Cause
        {
            get { return gsm0408Cause_; }
            set { selectGsm0408Cause(value); }
        }
        
                
          
        
	private long gsm0902MapErrorValue_ ;
        private bool  gsm0902MapErrorValue_selected = false ;
        
        
        
        [ASN1Element ( Name = "gsm0902MapErrorValue", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    [ASN1Integer( Name = "" )]
    
        public long Gsm0902MapErrorValue
        {
            get { return gsm0902MapErrorValue_; }
            set { selectGsm0902MapErrorValue(value); }
        }
        
                
          
        
	private long ccittQ767Cause_ ;
        private bool  ccittQ767Cause_selected = false ;
        
        
        
        [ASN1Element ( Name = "ccittQ767Cause", IsOptional =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    [ASN1Integer( Name = "" )]
    
        public long CcittQ767Cause
        {
            get { return ccittQ767Cause_; }
            set { selectCcittQ767Cause(value); }
        }
        
                
          
        
	private ManagementExtension networkSpecificCause_ ;
        private bool  networkSpecificCause_selected = false ;
        
        
        
        [ASN1Element ( Name = "networkSpecificCause", IsOptional =  false , HasTag =  true, Tag = 3 , HasDefaultValue =  false )  ]
    
        public ManagementExtension NetworkSpecificCause
        {
            get { return networkSpecificCause_; }
            set { selectNetworkSpecificCause(value); }
        }
        
                
          
        
	private ManagementExtension manufacturerSpecificCause_ ;
        private bool  manufacturerSpecificCause_selected = false ;
        
        
        
        [ASN1Element ( Name = "manufacturerSpecificCause", IsOptional =  false , HasTag =  true, Tag = 4 , HasDefaultValue =  false )  ]
    
        public ManagementExtension ManufacturerSpecificCause
        {
            get { return manufacturerSpecificCause_; }
            set { selectManufacturerSpecificCause(value); }
        }
        
                
          
        public bool isGsm0408CauseSelected () {
            return this.gsm0408Cause_selected ;
        }

        


        public void selectGsm0408Cause (long val) {
            this.gsm0408Cause_ = val;
            this.gsm0408Cause_selected = true;
            
            
                    this.gsm0902MapErrorValue_selected = false;
                
                    this.ccittQ767Cause_selected = false;
                
                    this.networkSpecificCause_selected = false;
                
                    this.manufacturerSpecificCause_selected = false;
                            
        }
        
          
        public bool isGsm0902MapErrorValueSelected () {
            return this.gsm0902MapErrorValue_selected ;
        }

        


        public void selectGsm0902MapErrorValue (long val) {
            this.gsm0902MapErrorValue_ = val;
            this.gsm0902MapErrorValue_selected = true;
            
            
                    this.gsm0408Cause_selected = false;
                
                    this.ccittQ767Cause_selected = false;
                
                    this.networkSpecificCause_selected = false;
                
                    this.manufacturerSpecificCause_selected = false;
                            
        }
        
          
        public bool isCcittQ767CauseSelected () {
            return this.ccittQ767Cause_selected ;
        }

        


        public void selectCcittQ767Cause (long val) {
            this.ccittQ767Cause_ = val;
            this.ccittQ767Cause_selected = true;
            
            
                    this.gsm0408Cause_selected = false;
                
                    this.gsm0902MapErrorValue_selected = false;
                
                    this.networkSpecificCause_selected = false;
                
                    this.manufacturerSpecificCause_selected = false;
                            
        }
        
          
        public bool isNetworkSpecificCauseSelected () {
            return this.networkSpecificCause_selected ;
        }

        


        public void selectNetworkSpecificCause (ManagementExtension val) {
            this.networkSpecificCause_ = val;
            this.networkSpecificCause_selected = true;
            
            
                    this.gsm0408Cause_selected = false;
                
                    this.gsm0902MapErrorValue_selected = false;
                
                    this.ccittQ767Cause_selected = false;
                
                    this.manufacturerSpecificCause_selected = false;
                            
        }
        
          
        public bool isManufacturerSpecificCauseSelected () {
            return this.manufacturerSpecificCause_selected ;
        }

        


        public void selectManufacturerSpecificCause (ManagementExtension val) {
            this.manufacturerSpecificCause_ = val;
            this.manufacturerSpecificCause_selected = true;
            
            
                    this.gsm0408Cause_selected = false;
                
                    this.gsm0902MapErrorValue_selected = false;
                
                    this.ccittQ767Cause_selected = false;
                
                    this.networkSpecificCause_selected = false;
                            
        }
        
  

            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(Diagnostics));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
