
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace GPRSber {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "GSNAddress") ]
    public class GSNAddress: IASN1PreparedElement {
            
           
        private IPAddress  val;

        
        [ASN1Element ( Name = "GSNAddress", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public IPAddress Value
        {
                get { return val; }        
                    
                set { val = value; }
                        
        }            

                    
        
        public GSNAddress ()
        {
        }

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(GSNAddress));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

        
    }
            
}
