
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace GPRSber {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "ManagementExtensions" ) ]
    public class ManagementExtensions : IASN1PreparedElement {

	    private System.Collections.Generic.ICollection<ManagementExtension> val = null; 
            
            
            [ASN1SequenceOf( Name = "ManagementExtensions", IsSetOf = true) ]

            public System.Collections.Generic.ICollection<ManagementExtension> Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public void initValue() {
                this.Value = new System.Collections.Generic.List<ManagementExtension>();
            }
            
            public void Add(ManagementExtension item) {
                this.Value.Add(item);
            }

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ManagementExtensions));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
