
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace GPRSber {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "QoSMeanThroughput")]
    public class QoSMeanThroughput : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "bestEffort", HasTag = true , Tag = 0 )]
            bestEffort , 
            [ASN1EnumItem ( Name = "mean100octetPh", HasTag = true , Tag = 1 )]
            mean100octetPh , 
            [ASN1EnumItem ( Name = "mean200octetPh", HasTag = true , Tag = 2 )]
            mean200octetPh , 
            [ASN1EnumItem ( Name = "mean500octetPh", HasTag = true , Tag = 3 )]
            mean500octetPh , 
            [ASN1EnumItem ( Name = "mean1000octetPh", HasTag = true , Tag = 4 )]
            mean1000octetPh , 
            [ASN1EnumItem ( Name = "mean2000octetPh", HasTag = true , Tag = 5 )]
            mean2000octetPh , 
            [ASN1EnumItem ( Name = "mean5000octetPh", HasTag = true , Tag = 6 )]
            mean5000octetPh , 
            [ASN1EnumItem ( Name = "mean10000octetPh", HasTag = true , Tag = 7 )]
            mean10000octetPh , 
            [ASN1EnumItem ( Name = "mean20000octetPh", HasTag = true , Tag = 8 )]
            mean20000octetPh , 
            [ASN1EnumItem ( Name = "mean50000octetPh", HasTag = true , Tag = 9 )]
            mean50000octetPh , 
            [ASN1EnumItem ( Name = "mean100000octetPh", HasTag = true , Tag = 10 )]
            mean100000octetPh , 
            [ASN1EnumItem ( Name = "mean200000octetPh", HasTag = true , Tag = 11 )]
            mean200000octetPh , 
            [ASN1EnumItem ( Name = "mean500000octetPh", HasTag = true , Tag = 12 )]
            mean500000octetPh , 
            [ASN1EnumItem ( Name = "mean1000000octetPh", HasTag = true , Tag = 13 )]
            mean1000000octetPh , 
            [ASN1EnumItem ( Name = "mean2000000octetPh", HasTag = true , Tag = 14 )]
            mean2000000octetPh , 
            [ASN1EnumItem ( Name = "mean5000000octetPh", HasTag = true , Tag = 15 )]
            mean5000000octetPh , 
            [ASN1EnumItem ( Name = "mean10000000octetPh", HasTag = true , Tag = 16 )]
            mean10000000octetPh , 
            [ASN1EnumItem ( Name = "mean20000000octetPh", HasTag = true , Tag = 17 )]
            mean20000000octetPh , 
            [ASN1EnumItem ( Name = "mean50000000octetPh", HasTag = true , Tag = 18 )]
            mean50000000octetPh , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }        

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(QoSMeanThroughput));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
    }
            
}
