
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace GPRSber {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "QoSReliability")]
    public class QoSReliability : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "unspecifiedReliability", HasTag = true , Tag = 0 )]
            unspecifiedReliability , 
            [ASN1EnumItem ( Name = "acknowledgedGTP", HasTag = true , Tag = 1 )]
            acknowledgedGTP , 
            [ASN1EnumItem ( Name = "unackGTPAcknowLLC", HasTag = true , Tag = 2 )]
            unackGTPAcknowLLC , 
            [ASN1EnumItem ( Name = "unackGTPLLCAcknowRLC", HasTag = true , Tag = 3 )]
            unackGTPLLCAcknowRLC , 
            [ASN1EnumItem ( Name = "unackGTPLLCRLC", HasTag = true , Tag = 4 )]
            unackGTPLLCRLC , 
            [ASN1EnumItem ( Name = "unacknowUnprotectedData", HasTag = true , Tag = 5 )]
            unacknowUnprotectedData
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }        

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(QoSReliability));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
    }
            
}
