
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace GPRSber {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "RECORDSequenceNumber", IsSet = false  )]
    public class RECORDSequenceNumber : IASN1PreparedElement {
                    
	private GSNAddress gsnAddress_ ;
	
        [ASN1Element ( Name = "gsnAddress", IsOptional =  false , HasTag =  true, Tag = 0, IsImplicitTag = false  , HasDefaultValue =  false )  ]
    
        public GSNAddress GsnAddress
        {
            get { return gsnAddress_; }
            set { gsnAddress_ = value;  }
        }
        
                
          
	private System.Collections.Generic.ICollection<RecordNumber> recordNumberList_ ;
	
[ASN1SequenceOf( Name = "", IsSetOf = false  )]

    
        [ASN1Element ( Name = "recordNumberList", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public System.Collections.Generic.ICollection<RecordNumber> RecordNumberList
        {
            get { return recordNumberList_; }
            set { recordNumberList_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
            	
            }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(RECORDSequenceNumber));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
