
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace GPRSber {


    [ASN1PreparedElement]
    [ASN1Choice ( Name = "CallEventRecord") ]
    public class CallEventRecord : IASN1PreparedElement {
                    
        
	private SGSNPDPRecord sgsnPDPRecord_ ;
        private bool  sgsnPDPRecord_selected = false ;
        
        
        
        [ASN1Element ( Name = "sgsnPDPRecord", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public SGSNPDPRecord SgsnPDPRecord
        {
            get { return sgsnPDPRecord_; }
            set { selectSgsnPDPRecord(value); }
        }
        
                
          
        
	private GGSNPDPRecord ggsnPDPRecord_ ;
        private bool  ggsnPDPRecord_selected = false ;
        
        
        
        [ASN1Element ( Name = "ggsnPDPRecord", IsOptional =  false , HasTag =  true, Tag = 1 , HasDefaultValue =  false )  ]
    
        public GGSNPDPRecord GgsnPDPRecord
        {
            get { return ggsnPDPRecord_; }
            set { selectGgsnPDPRecord(value); }
        }
        
                
          
        
	private SGSNMMRecord sgsnMMRecord_ ;
        private bool  sgsnMMRecord_selected = false ;
        
        
        
        [ASN1Element ( Name = "sgsnMMRecord", IsOptional =  false , HasTag =  true, Tag = 2 , HasDefaultValue =  false )  ]
    
        public SGSNMMRecord SgsnMMRecord
        {
            get { return sgsnMMRecord_; }
            set { selectSgsnMMRecord(value); }
        }
        
                
          
        
	private SGSNSMORecord sgsnSMORecord_ ;
        private bool  sgsnSMORecord_selected = false ;
        
        
        
        [ASN1Element ( Name = "sgsnSMORecord", IsOptional =  false , HasTag =  true, Tag = 3 , HasDefaultValue =  false )  ]
    
        public SGSNSMORecord SgsnSMORecord
        {
            get { return sgsnSMORecord_; }
            set { selectSgsnSMORecord(value); }
        }
        
                
          
        
	private SGSNSMTRecord sgsnSMTRecord_ ;
        private bool  sgsnSMTRecord_selected = false ;
        
        
        
        [ASN1Element ( Name = "sgsnSMTRecord", IsOptional =  false , HasTag =  true, Tag = 4 , HasDefaultValue =  false )  ]
    
        public SGSNSMTRecord SgsnSMTRecord
        {
            get { return sgsnSMTRecord_; }
            set { selectSgsnSMTRecord(value); }
        }
        
                
          
        public bool isSgsnPDPRecordSelected () {
            return this.sgsnPDPRecord_selected ;
        }

        


        public void selectSgsnPDPRecord (SGSNPDPRecord val) {
            this.sgsnPDPRecord_ = val;
            this.sgsnPDPRecord_selected = true;
            
            
                    this.ggsnPDPRecord_selected = false;
                
                    this.sgsnMMRecord_selected = false;
                
                    this.sgsnSMORecord_selected = false;
                
                    this.sgsnSMTRecord_selected = false;
                            
        }
        
          
        public bool isGgsnPDPRecordSelected () {
            return this.ggsnPDPRecord_selected ;
        }

        


        public void selectGgsnPDPRecord (GGSNPDPRecord val) {
            this.ggsnPDPRecord_ = val;
            this.ggsnPDPRecord_selected = true;
            
            
                    this.sgsnPDPRecord_selected = false;
                
                    this.sgsnMMRecord_selected = false;
                
                    this.sgsnSMORecord_selected = false;
                
                    this.sgsnSMTRecord_selected = false;
                            
        }
        
          
        public bool isSgsnMMRecordSelected () {
            return this.sgsnMMRecord_selected ;
        }

        


        public void selectSgsnMMRecord (SGSNMMRecord val) {
            this.sgsnMMRecord_ = val;
            this.sgsnMMRecord_selected = true;
            
            
                    this.sgsnPDPRecord_selected = false;
                
                    this.ggsnPDPRecord_selected = false;
                
                    this.sgsnSMORecord_selected = false;
                
                    this.sgsnSMTRecord_selected = false;
                            
        }
        
          
        public bool isSgsnSMORecordSelected () {
            return this.sgsnSMORecord_selected ;
        }

        


        public void selectSgsnSMORecord (SGSNSMORecord val) {
            this.sgsnSMORecord_ = val;
            this.sgsnSMORecord_selected = true;
            
            
                    this.sgsnPDPRecord_selected = false;
                
                    this.ggsnPDPRecord_selected = false;
                
                    this.sgsnMMRecord_selected = false;
                
                    this.sgsnSMTRecord_selected = false;
                            
        }
        
          
        public bool isSgsnSMTRecordSelected () {
            return this.sgsnSMTRecord_selected ;
        }

        


        public void selectSgsnSMTRecord (SGSNSMTRecord val) {
            this.sgsnSMTRecord_ = val;
            this.sgsnSMTRecord_selected = true;
            
            
                    this.sgsnPDPRecord_selected = false;
                
                    this.ggsnPDPRecord_selected = false;
                
                    this.sgsnMMRecord_selected = false;
                
                    this.sgsnSMORecord_selected = false;
                            
        }
        
  

            public void initWithDefaults()
	    {
	    }

            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(CallEventRecord));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
