
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace GPRSber {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "ConsolidationResult")]
    public class ConsolidationResult : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "normal", HasTag = true , Tag = 0 )]
            normal , 
            [ASN1EnumItem ( Name = "notNormal", HasTag = true , Tag = 1 )]
            notNormal , 
            [ASN1EnumItem ( Name = "forInterSGSNConsolidation", HasTag = true , Tag = 2 )]
            forInterSGSNConsolidation , 
            [ASN1EnumItem ( Name = "reachLimit", HasTag = true , Tag = 3 )]
            reachLimit , 
            [ASN1EnumItem ( Name = "onlyOneCDRGenerated", HasTag = true , Tag = 4 )]
            onlyOneCDRGenerated , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }        

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(ConsolidationResult));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
    }
            
}
