
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace GPRSber {


    [ASN1PreparedElement]
    [ASN1BoxedType ( Name = "LocalSequenceNumber" )]
    public class LocalSequenceNumber: IASN1PreparedElement {
    
            private long val;
            
            [ASN1Integer( Name = "LocalSequenceNumber" )]
            [ASN1ValueRangeConstraint ( 
		
		Min = 0L, 
		
		Max = 4294967295L 
		
		) ]
	    
            public long Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public LocalSequenceNumber() {
            }

            public LocalSequenceNumber(long value) {
                this.Value = value;
            }            

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(LocalSequenceNumber));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

    }
            
}
