
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace GPRSber {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "QoSDelay")]
    public class QoSDelay : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "delayClass1", HasTag = true , Tag = 1 )]
            delayClass1 , 
            [ASN1EnumItem ( Name = "delayClass2", HasTag = true , Tag = 2 )]
            delayClass2 , 
            [ASN1EnumItem ( Name = "delayClass3", HasTag = true , Tag = 3 )]
            delayClass3 , 
            [ASN1EnumItem ( Name = "delayClass4", HasTag = true , Tag = 4 )]
            delayClass4 , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }        

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(QoSDelay));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
    }
            
}
