
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;
using org.bn;

namespace GPRSber {


    [ASN1PreparedElement]
    [ASN1Enum ( Name = "QoSPeakThroughput")]
    public class QoSPeakThroughput : IASN1PreparedElement {        
        public enum EnumType {
            
            [ASN1EnumItem ( Name = "unspecified", HasTag = true , Tag = 0 )]
            unspecified , 
            [ASN1EnumItem ( Name = "upTo100OctetPs", HasTag = true , Tag = 1 )]
            upTo100OctetPs , 
            [ASN1EnumItem ( Name = "upTo200OctetPs", HasTag = true , Tag = 2 )]
            upTo200OctetPs , 
            [ASN1EnumItem ( Name = "upTo400OctetPs", HasTag = true , Tag = 3 )]
            upTo400OctetPs , 
            [ASN1EnumItem ( Name = "upTo800OctetPs", HasTag = true , Tag = 4 )]
            upTo800OctetPs , 
            [ASN1EnumItem ( Name = "upTo1600OctetPs", HasTag = true , Tag = 5 )]
            upTo1600OctetPs , 
            [ASN1EnumItem ( Name = "upTo3200OctetPs", HasTag = true , Tag = 6 )]
            upTo3200OctetPs , 
            [ASN1EnumItem ( Name = "upTo6400OctetPs", HasTag = true , Tag = 7 )]
            upTo6400OctetPs , 
            [ASN1EnumItem ( Name = "upTo12800OctetPs", HasTag = true , Tag = 8 )]
            upTo12800OctetPs , 
            [ASN1EnumItem ( Name = "upTo25600OctetPs", HasTag = true , Tag = 9 )]
            upTo25600OctetPs , 
        }
        
        private EnumType val;
        
        public EnumType Value
        {
            get { return val; }
            set { val = value; }
        }        

            public void initWithDefaults()
	    {
	    }


            private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(typeof(QoSPeakThroughput));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

                
    }
            
}
